version: "3.8"

services:
  traefik:
    image: traefik:v3
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --api.dashboard=true
      - --api.insecure=true  # Only for dev!
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.drogaprogramisty.site`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.services.api.loadbalancer.server.url=http://host.docker.internal:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"