services:
  traefik:
    image: traefik:v3
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      # todo - if I want to use labels-based configuration, I must use providers.docker=true, but if I have not-dockerised app, I could fall back to file-based configuration instead.
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.my-resolver.acme.tlschallenge=true"
      - "--certificatesresolvers.my-resolver.acme.email=drogaprogramisty@gmail.com"
      - "--certificatesresolvers.my-resolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--api.dashboard=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hello-world-router.rule=Host(`api.drogaprogramisty.site`)"
      - "traefik.http.routers.hello-world-router.entrypoints=websecure"
      - "traefik.http.routers.hello-world-router.service=hello-world-service"
      - "traefik.http.routers.hello-world-router.tls.certResolver=my-resolver"
      - "traefik.http.services.hello-world-service.loadbalancer.server.url=http://host.docker.internal:3000"
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.drogaprogramisty.site`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth"
      - "traefik.http.routers.dashboard.tls.certResolver=my-resolver"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      # admin / traefik, please change!
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=admin:$$2a$$12$$ktgZsFQZ0S1FeQbI1JjS9u36fAJMHDQaY6LNi9EkEp8sKtP5BK43C"

    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  letsencrypt: